services:
  - type: web
    name: fleet-management-backoffice
    runtime: image
    image:
      url: ghcr.io/farsuller/fleet-management-backoffice:latest
      creds:
        fromRegistryCreds:
          name: ghcr-read-credentials
    healthCheckPath: /
    envVars:
      - key: FLEET_API_BASE_URL
        sync: false
      - key: FLEET_WS_BASE_URL
        sync: false
